

services:
  web:
    build: .
    ports:
      - "8001:8001"
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DB_NAME=nafass_backend
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: nafass_backend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
